### PR TITLE
clpz mod

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
This implementation is inspired from [clpz_power](https://github.com/triska/scryer-prolog/pull/1). The commit is 2a14b67.

The predicate `queue_goal//1` is being used everything, this isn't optimal yet. Bound update is missing and the code still needs some simplification. It doesn't seem like anything else can be done in `pmodx`, it should be removed.

The next step is exhaustive test.

**Comment by ghost** [comment]
The predicate `fd_put/3` is used instead of `queue_goal//1`, simplified the code a bit, added tests. Added bound update but one is missing:
```
?- Z #= X mod Y, Y #=< 6.
   clpz:(X mod Y#=Z), clpz:(Y in inf.. -1\/1..6)
;  false.
?- 
```
While the expected result:
```
?- Z #= X mod Y, Y #=< 6.
   clpz:(X mod Y#=Z), clpz:(Y in inf.. -1\/1..6), clpz:(Z in inf..5)
;  false.
?- 
```
It can be triggered with:
```
?- Z #= X mod Y, Y #=< 6, Z #< 10.
   clpz:(X mod Y#=Z), clpz:(Y in inf.. -1\/1..6), clpz:(Z in inf..5)
;  false.
?-
```
I don't understand the issue at this [line](https://github.com/triska/scryer-prolog/blob/0b16dde36980df2d43cfa733c5d3df878510d61d/src/lib/clpz.pl#L5187).

After that issue is solved, tests are run (and a formatting commit), this PR is good to get merged.

**Comment by triska** [comment]
Thank you a lot for working on this!

I have now pushed all latest commits from Mark's branch to this master branch. Why are there still so many commits in this pull request? Could you please rebase against the latest version to make it easier to review what has actually changed with respect to master?

What exactly is the issue at that line, does it yield wrong results?

**Comment by ghost** [comment]
The bound of `Z` isn't updated:
```
?- Z #= X mod Y, Y #=< 6.
   clpz:(X mod Y#=Z), clpz:(Y in inf.. -1\/1..6)
;  false.
?- 
```
`clpz:(Z in inf..5)` is missing.

**Comment by ghost** [comment]
I see this happens:
```
?- Y #=< 6, Z #= X mod Y.
   clpz:(X mod Y#=Z), clpz:(Y in inf.. -1\/1..6), clpz:(Z in inf..5)
;  false.
?- 
```
Is this related to the infinity issue (`?- X #< Y, X #> Y, X #> 0`)?

**Comment by triska** [comment]
Perfect, thank you a lot, this looks very good!

Please file this exact pull request to Mark's repository: There, more people are watching, so let's use it for discussion!

**Comment by ghost** [comment]
OK, closing this.

**Pull request closed without merging**
